openapi: 3.0.0
info:
  title: Coordination Module API
  version: 1.0.0
components:
  schemas:
    Schedule:
      $ref: './schedule.yaml#/components/schemas'
    Course:
      $ref: './course.yaml#/components/schemas'
    CourseEvent:
      $ref: './course-event.yaml#/components/schemas'

paths:
  /schedules:
    $ref: './schedule.yaml#/paths/~1schedules'
  /schedules/{scheduleId}:
    $ref: './schedule.yaml#/paths/~1schedules~1{scheduleId}'
  /courses:
    $ref: './course.yaml#/paths/~1courses'
  /courses/{courseId}:
    $ref: './course.yaml#/paths/~1courses~1{courseId}'
  /course-events:
    $ref: './course-event.yaml#/paths/~1course-events'
  /course-events/{courseEventId}:
    $ref: './course-event.yaml#/paths/~1course-events~1{courseEventId}'