openapi: 3.0.0
info:
  title: Coordination Module API
  version: 1.0.0
  description: API to manage courses and activities calendar
components:
  schemas:
    Course:
      $ref: './course.yaml#/components/schemas'
    CourseEvent:
      $ref: './course-event.yaml#/components/schemas'
paths:
  /courses:
    $ref: './course.yaml#/paths/~1courses'
  /courses/{courseId}:
    $ref: './course.yaml#/paths/~1courses~1{courseId}'
  /course-events:
    $ref: './course-event.yaml#/paths/~1course-events'
  /course-events/{courseEventId}:
    $ref: './course-event.yaml#/paths/~1course-events~1{courseEventId}'