openapi: 3.0.0
info:
  title: Communication Module API
  version: 1.0.0
components:
  schemas:
    EmailCreationRequest:
      $ref: './email.yaml#/components/schemas/EmailCreationRequest'
    EmailResponse:
      $ref: './email.yaml#/components/schemas/EmailCreationResponse'
    GetEmailResponse:
      $ref: './email.yaml#/components/schemas/GetEmailResponse'
    ErrorResponse:
      $ref: './email.yaml#/components/schemas/ErrorResponse'
paths:
  /emails:
    $ref: './email.yaml#/paths/~1emails'
  /emails/{emailId}:
    $ref: './email.yaml#/paths/~1emails~1{emailId}'
  /emails/bySubject/{subject}:
    $ref: './email.yaml#/paths/~1emails~1bySubject~1{subject}'
  /emails/byRecipient/{recipient}:
    $ref: './email.yaml#/paths/~1emails~1byRecipient~1{recipient}'