openapi: 3.0.0
info:
  title:   Compensation Entity
  version: '1.0.0'
components:
  schemas:
    BaseCompensation:
      type: object
      properties:
        compensationType:
          type: string
          maxLength: 10
          description: Type of compensation (e.g., hourly, salary)
        amount:
          type: number
          format: double
          description: Amount of compensation
      required:
        - compensationType
        - amount
    CompensationCreationRequest:
      allOf:
        - $ref: '#/components/schemas/BaseCompensation'
    CompensationCreationResponse:
      type: object
      properties:
        compensationId:
          type: integer
          readOnly: true
          description: Compensation ID
      required:
        - compensationId
    GetCompensationResponse:
      allOf:
        - $ref: '#/components/schemas/BaseCompensation'
        - type: object
          properties:
            compensationId:
              type: integer
              readOnly: true
              description: Compensation ID
            instructorIds:
              type: array
              items:
                type: integer
              description: IDs of instructors associated with this compensation
          required:
            - compensationId
            - compensationType
            - amount
            - instructorIds
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          description: Error message
      required:
        - message
    InstructorAssociationRequest:
      type: object
      properties:
        instructorId:
          type: integer
          description: ID of the instructor to associate with the compensation
      required:
        - instructorId
    InstructorAssociationResponse:
      type: object
      properties:
        compensationId:
          type: integer
          readOnly: true
          description: Compensation ID
        instructorId:
          type: integer
          readOnly: true
          description: ID of the associated instructor
      required:
        - compensationId
        - instructorId
paths:
  '/compensations':
    post:
      summary: Create a new compensation
      operationId: createCompensation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CompensationCreationRequest'
      responses:
        '201':
          description: Compensation created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompensationCreationResponse'
        '400':
          description: Invalid request data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: An unexpected error occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    get:
      summary: Get all compensations
      operationId: getCompensations
      responses:
        '200':
          description: List of compensations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GetCompensationResponse'
        '500':
          description: An unexpected error occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  '/compensations/{compensationId}':
    get:
      summary: Get a compensation by ID
      operationId: getCompensationById
      parameters:
        - name: compensationId
          in: path
          required: true
          schema:
            type: integer
          description: ID of the compensation to retrieve
      responses:
        '200':
          description: Compensation details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetCompensationResponse'
        '404':
          description: Compensation not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: An unexpected error occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    put:
      summary: Update a compensation
      operationId: updateCompensation
      parameters:
        - name: compensationId
          in: path
          required: true
          schema:
            type: integer
          description: ID of the compensation to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CompensationCreationRequest'
      responses:
        '200':
          description: Compensation updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompensationCreationResponse'
        '400':
          description: Invalid request data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Compensation not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: An unexpected error occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    delete:
      summary: Delete a compensation
      operationId: deleteCompensation
      parameters:
        - name: compensationId
          in: path
          required: true
          schema:
            type: integer
          description: ID of the compensation to delete
      responses:
        '204':
          description: Compensation deleted successfully
        '404':
          description: Compensation not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: An unexpected error occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  '/compensations/{compensationId}/instructors':
    post:
      summary: Associate an instructor with a compensation
      operationId: associateInstructorWithCompensation
      parameters:
        - name: compensationId
          in: path
          required: true
          schema:
            type: integer
          description: ID of the compensation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InstructorAssociationRequest'
      responses:
        '200':
          description: Instructor associated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InstructorAssociationResponse'
        '400':
          description: Invalid request data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Compensation or Instructor not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: An unexpected error occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    delete:
      summary: Remove an instructor from a compensation
      operationId: removeInstructorFromCompensation
      parameters:
        - name: compensationId
          in: path
          required: true
          schema:
            type: integer
          description: ID of the compensation
        - name: instructorId
          in: path
          required: true
          schema:
            type: integer
          description: ID of the instructor to remove
      responses:
        '204':
          description: Instructor removed successfully
        '404':
          description: Compensation or Instructor not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: An unexpected error occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'