openapi: 3.0.0
info:
  title: Customer Services API
  version: 1.0.0
  description: API for managing customers in the Makani system
paths:
  /adultStudents:
    get:
      summary: Retrieve a list of adult students
      operationId: getAdultStudents
      responses:
        '200':
          description: A list of adult students
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AdultStudent'
        '500':
          description: An unexpected error occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    post:
      summary: Create a new adult student
      operationId: createAdultStudent
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AdultStudentCreateRequest'
      responses:
        '201':
          description: Adult student created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdultStudent'
        '400':
          description: Invalid request data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: An unexpected error occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /minorStudents:
    get:
      summary: Retrieve a list of minor students
      operationId: getMinorStudents
      responses:
        '200':
          description: A list of minor students
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MinorStudent'
        '500':
          description: An unexpected error occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    post:
      summary: Create a new minor student
      operationId: createMinorStudent
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MinorStudentCreateRequest'
      responses:
        '201':
          description: Minor student created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MinorStudent'
        '400':
          description: Invalid request data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: An unexpected error occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    BaseStudent:
      type: object
      properties:
        profilePicture:
          type: string
          format: byte
        customerAuthId:
          type: integer
    AdultStudent:
      allOf:
        - $ref: '#/components/schemas/BaseStudent'
        - type: object
          properties:
            adultStudentId:
              type: integer
    MinorStudent:
      allOf:
        - $ref: '#/components/schemas/BaseStudent'
        - type: object
          properties:
            minorStudentId:
              type: integer
            tutorId:
              type: integer
    Tutor:
      type: object
      properties:
        tutorId:
          type: integer
        customerAuthId:
          type: integer
    CustomerAuth:
      type: object
      properties:
        customerAuthId:
          type: integer
        provider:
          type: string
          maxLength: 9
        token:
          type: string
          format: byte
    AdultStudentCreateRequest:
      type: object
      properties:
        profilePicture:
          type: string
          format: byte
        customerAuthId:
          type: integer
    MinorStudentCreateRequest:
      type: object
      properties:
        profilePicture:
          type: string
          format: byte
        customerAuthId:
          type: integer
        tutorId:
          type: integer
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
        details:
          type: string