openapi: 3.0.0
info:
  title: Customer Services API
  version: 1.0.0
  description: API for managing customers in the Makani system

paths:
  /adultStudents:
    get:
      summary: Retrieve a list of adult students
      operationId: getAdultStudents
      responses:
        '200':
          description: A list of adult students
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AdultStudent'
        '500':
          description: An unexpected error occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    post:
      summary: Create a new adult student
      operationId: createAdultStudent
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AdultStudentCreateRequest'
      responses:
        '201':
          description: Adult student created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdultStudent'
        '400':
          description: Invalid request data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: An unexpected error occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /minorStudents:
    get:
      summary: Retrieve a list of minor students
      operationId: getMinorStudents
      responses:
        '200':
          description: A list of minor students
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MinorStudent'
        '500':
          description: An unexpected error occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    post:
      summary: Create a new minor student
      operationId: createMinorStudent
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MinorStudentCreateRequest'
      responses:
        '201':
          description: Minor student created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MinorStudent'
        '400':
          description: Invalid request data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: An unexpected error occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    BaseStudent:
      type: object
      properties:
        profilePicture:
          type: string
          format: byte
        customerAuthId:
          type: integer

    AdultStudent:
      allOf:
        - $ref: './commons.yaml#/components/schemas/BasePerson'
        - $ref: '#/components/schemas/BaseStudent'

    MinorStudent:
      allOf:
        - $ref: '#/components/schemas/BaseStudent'
        - $ref: '#/components/schemas/Tutor'
        - type: object
          properties:
            tutorId:
              type: integer
            customerAuthId:
              type: integer

    Tutor:
      allOf:
        - $ref: './commons.yaml#/components/schemas/BasePerson'

    CustomerAuth:
      type: object
      properties:
        customerAuthId:
          type: integer
        provider:
          type: string
          maxLength: 9
        token:
          type: string
          format: byte

    AdultStudentCreateRequest:
      allOf:
        - $ref: '#/components/schemas/AdultStudent'
        - type: object
          properties:
            auth:
              $ref: '#/components/schemas/CustomerAuth'

    AdultStudentResponse:
      allOf:
        - $ref: '#/components/schemas/AdultStudent'
        - type: object
          properties:
            adultStudentId:
              type: integer

    MinorStudentCreateRequest:
      allOf:
        - $ref: '#/components/schemas/MinorStudent'
        - type: object
          properties:
            minorStudentAuth:
              $ref: '#/components/schemas/CustomerAuth'
            tutorAuth:
              $ref: '#/components/schemas/CustomerAuth'

    MinorStudentResponse:
      allOf:
        - $ref: '#/components/schemas/MinorStudent'
        - type: object
          properties:
            minorStudentId:
              type: integer

    ErrorResponse:
      type: object
      properties:
        message:
          type: string
        details:
          type: string
