openapi: 3.0.0
info:
  title: Employee Services API
  version: 1.0.0
  description: API for managing people in the Makani system

paths:
  /employee:
    post:
      operationId: postEmployee
      summary: Create a new employee
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmployeeCreateRequest'
      responses:
        '201':
          description: Employee created successfully
          content:
            application/json:
              schema:
                type: integer
        '400':
          description: Invalid request data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Employee not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: An unexpected error occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    get:
      summary: Retrieve an employee by ID
      operationId: getEmployeeById
      parameters:
        - in: query
          name: employeeId
          schema:
            type: integer
          required: true
          description: ID of the employee to retrieve
      responses:
        '200':
          description: Employee retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmployeeResponse'
        '404':
          description: Employee not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: An unexpected error occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    EmployeeCreateRequest:
      allOf:
        - $ref: './commons.yaml#/components/schemas/BasePerson'
        - type: object
          properties:
            employeeAuth:
              $ref: './commons.yaml#/components/schemas/InternalAuth'
          required:
            - firstName
            - lastName
            - email
            - phone
            - address
            - zipCode
            - birthDate
            - employeeType
            - usernameToken
            - passwordToken

    EmployeeResponse:
      allOf:
        - $ref: './commons.yaml#/components/schemas/BasePerson'
        - type: object
          properties:
            employeeId:
              type: integer
              description: Employee ID
          required:
            - employeeId
            - firstName
            - lastName
            - birthDate
            - email
            - phone
            - address
            - zipCode

    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          description: Error message
