openapi: 3.0.0
info:
  title: Instructor Services API
  version: 1.0.0
  description: API for managing instructors in the Makani system

paths:
  /instructor:
    get:
      summary: Retrieve a list of instructors
      operationId: getInstructors
      responses:
        '200':
          description: A list of instructors
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/InstructorResponse'
        '500':
          description: An unexpected error occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    post:
      summary: Create a new instructor
      operationId: createInstructor
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InstructorCreateRequest'
      responses:
        '201':
          description: Instructor created successfully
          content:
            application/json:
              schema:
                type: integer
        '400':
          description: Invalid request data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: An unexpected error occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /instructors/{instructorId}:
    get:
      summary: Retrieve an instructor by ID
      operationId: getInstructorById
      parameters:
        - in: path
          name: instructorId
          required: true
          schema:
            type: integer
          description: ID of the instructor to retrieve
      responses:
        '200':
          description: Instructor retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InstructorResponse'
        '404':
          description: Instructor not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: An unexpected error occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    Instructor:
      allOf:
        - $ref: './commons.yaml#/components/schemas/BasePerson'
        - type: object
          properties:
            skills:
              type: string
              maxLength: 100
              nullable: true
            profilePicture:
              type: string
              format: byte

    InstructorCreateRequest:
      allOf:
        - $ref: '#/components/schemas/Instructor'
        - $ref: './commons.yaml#/components/schemas/InternalAuth'

    InstructorResponse:
      allOf:
        - $ref: '#/components/schemas/Instructor'
        - type: object
          properties:
            instructorId:
              type: integer
              description: Instructor ID

    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          description: Error message
